In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("data/data21.csv")
df2 = pd.read_csv("data/data22.csv")
df2.rename(columns={column: column + "2" for column in df2.columns}, inplace=True)
df = pd.concat([df1, df2], axis=1)

In [3]:
df['Material'].fillna("None", inplace=True)
df['Material2'].fillna("None", inplace=True)

In [4]:
df.loc[(df['Time'] != df['Time2']) | (df['Resource'] != df['Resource2']) | (df['Material'] != df['Material2'])]

,Unnamed: 0,Time,Resource,State,Activity,Material,Expected End Time,Target location,Unnamed: 02,Time2,Resource2,State2,Activity2,Material2,Expected End Time2,Target location2
7174,7174.0,4614.564922,TR2,TP1,end state,Material_1 instance N.290,4614.564922,R1,7174,4615.231589,TR2,TP1,end state,Material_1 instance N.290,4615.231589,R3
7181,7181.0,4618.246079,TR1,TP1,end state,Material_3 instance N.289,4618.246079,R3,7181,4618.579413,TR1,TP1,end state,Material_3 instance N.289,4618.579413,R2
7185,7185.0,4621.826674,TR1,TP1,start state,Material_2 instance N.271,4622.310007,R2,7185,4621.826674,R2,P2,start state,Material_3 instance N.263,4636.826674,NaN
7186,7186.0,4621.826674,R2,P2,start state,Material_3 instance N.263,4636.826674,NaN,7186,4622.052359,TR2,TP1,end state,Material_2 instance N.273,4622.052359,R1
7187,7187.0,4622.052359,TR2,TP1,end state,Material_2 instance N.273,4622.052359,R3,7187,4622.052359,TR2,TP1,start state,Material_2 instance N.271,4622.535692,R2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68412,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,68412,39996.080548,TR1,TP1,start state,Material_2 instance N.2632,39996.563881,R1
68413,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,68413,39996.563881,TR1,TP1,end state,Material_2 instance N.2632,39996.563881,R1
68414,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,68414,39996.986564,TR2,TP1,end state,Material_1 instance N.2637,39996.986564,S1
68415,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,68415,39996.986564,TR2,TP1,start state,Material_1 instance N.2637,39997.803230,R1
68416,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,68416,39997.803230,TR2,TP1,end state,Material_1 instance N.2637,39997.803230,R1