In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("data/data21.csv")
df2 = pd.read_csv("data/data22.csv")
df2.rename(columns={column: column + "2" for column in df2.columns}, inplace=True)
df = pd.concat([df1, df2], axis=1)

In [3]:
df['Material'].fillna("None", inplace=True)
df['Material2'].fillna("None", inplace=True)

In [4]:
df.loc[(df['Time'] != df['Time2']) | (df['Resource'] != df['Resource2']) | (df['Material'] != df['Material2'])]

,Unnamed: 0,Time,Resource,State,Activity,Material,Expected End Time,Target location,Unnamed: 02,Time2,Resource2,State2,Activity2,Material2,Expected End Time2,Target location2
7174,7174.0,4614.564922,TR2,TP1,end state,Material_1 instance N.290,4614.564922,R1,7174,4615.231589,TR2,TP1,end state,Material_1 instance N.290,4615.231589,R3
7181,7181.0,4618.246079,TR1,TP1,end state,Material_3 instance N.289,4618.246079,R3,7181,4618.579413,TR1,TP1,end state,Material_3 instance N.289,4618.579413,R2
7185,7185.0,4621.826674,TR1,TP1,start state,Material_2 instance N.271,4622.310007,R2,7185,4621.826674,R2,P2,start state,Material_3 instance N.263,4636.826674,NaN
7186,7186.0,4621.826674,R2,P2,start state,Material_3 instance N.263,4636.826674,NaN,7186,4622.052359,TR2,TP1,end state,Material_2 instance N.273,4622.052359,R1
7187,7187.0,4622.052359,TR2,TP1,end state,Material_2 instance N.273,4622.052359,R3,7187,4622.052359,TR2,TP1,start state,Material_2 instance N.271,4622.535692,R2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68412,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,68412,39996.080548,TR1,TP1,start state,Material_2 instance N.2632,39996.563881,R1
68413,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,68413,39996.563881,TR1,TP1,end state,Material_2 instance N.2632,39996.563881,R1
68414,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,68414,39996.986564,TR2,TP1,end state,Material_1 instance N.2637,39996.986564,S1
68415,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,68415,39996.986564,TR2,TP1,start state,Material_1 instance N.2637,39997.803230,R1
68416,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,68416,39997.803230,TR2,TP1,end state,Material_1 instance N.2637,39997.803230,R1

In [12]:
df.loc[df['Material'] == "Material_3 instance N.289"]

,Unnamed: 0,Time,Resource,State,Activity,Material,Expected End Time,Target location,Unnamed: 02,Time2,Resource2,State2,Activity2,Material2,Expected End Time2,Target location2
7161,7161.0,4610.779851,S3,S3,created material,Material_3 instance N.289,NaN,NaN,7161,4610.779851,S3,S3,created material,Material_3 instance N.289,NaN,NaN
7178,7178.0,4615.946079,TR1,TP1,start state,Material_3 instance N.289,4617.096079,S3,7178,4615.946079,TR1,TP1,start state,Material_3 instance N.289,4617.096079,S3
7179,7179.0,4617.096079,TR1,TP1,end state,Material_3 instance N.289,4617.096079,S3,7179,4617.096079,TR1,TP1,end state,Material_3 instance N.289,4617.096079,S3
7180,7180.0,4617.096079,TR1,TP1,start state,Material_3 instance N.289,4618.246079,R3,7180,4617.096079,TR1,TP1,start state,Material_3 instance N.289,4618.579413,R2
7181,7181.0,4618.246079,TR1,TP1,end state,Material_3 instance N.289,4618.246079,R3,7181,4618.579413,TR1,TP1,end state,Material_3 instance N.289,4618.579413,R2
7257,7257.0,4656.543678,R3,P3,start state,Material_3 instance N.289,4680.157177,NaN,7257,4657.843678,TR1,TP1,end state,Material_1 instance N.288,4657.843678,R1
7317,7317.0,4680.157177,R3,P3,end state,Material_3 instance N.289,4680.157177,NaN,7317,4684.745256,TR2,TP1,start state,Material_2 instance N.291,4685.228589,R3
7318,7318.0,4680.157177,TR1,TP1,start state,Material_3 instance N.289,4680.973844,R3,7318,4684.745256,R3,P1,start state,Material_2 instance N.260,4703.888169,NaN
7320,7320.0,4680.973844,TR1,TP1,end state,Material_3 instance N.289,4680.973844,R3,7320,4684.884193,TR1,TP1,start state,Material_1 instance N.292,4685.367527,R1
7321,7321.0,4680.973844,TR1,TP1,start state,Material_3 instance N.289,4681.790511,R1,7321,4685.228589,TR2,TP1,end state,Material_2 instance N.291,4685.228589,R3
7322,7322.0,4681.790511,TR1,TP1,end state,Material_3 instance N.289,4681.790511,R1,7322,4685.228589,TR2,TP1,start state,Material_2 instance N.291,4686.045256,R1
7489,7489.0,4754.084744,R1,P2,start state,Material_3 instance N.289,4769.084744,NaN,7489,4757.726863,R1,P1,end state,Material_1 instance N.293,4757.726863,NaN
7538,7538.0,4769.084744,R1,P2,end state,Material_3 instance N.289,4769.084744,NaN,7538,4783.634122,SK1,SK1,finished material,Material_1 instance N.276,NaN,NaN
7540,7540.0,4769.084744,TR1,TP1,start state,Material_3 instance N.289,4769.234744,R1,7540,4787.726863,R1,P2,end state,Material_1 instance N.292,4787.726863,NaN
7541,7541.0,4769.234744,TR1,TP1,end state,Material_3 instance N.289,4769.234744,R1,7541,4787.726863,R1,P2,start state,Material_2 instance N.291,4802.726863,NaN
7660,7660.0,4844.501882,R1,P1,start state,Material_3 instance N.289,4860.211022,NaN,7660,4844.488829,TR1,TP1,start state,Material_3 instance N.296,4845.305495,R4
7709,7709.0,4860.211022,R1,P1,end state,Material_3 instance N.289,4860.211022,NaN,7709,4864.475676,TR2,TP1,start state,Material_2 instance N.302,4864.959009,R1
7710,7710.0,4860.211022,TR1,TP1,start state,Material_3 instance N.289,4863.027688,R1,7710,4864.475676,R1,P2,start state,Material_2 instance N.305,4879.475676,NaN
7715,7715.0,4863.027688,TR1,TP1,end state,Material_3 instance N.289,4863.027688,R1,7715,4865.775676,TR2,TP1,end state,Material_2 instance N.302,4865.775676,R3
7716,7716.0,4863.027688,TR1,TP1,start state,Material_3 instance N.289,4865.677688,SK3,7716,4865.775676,TR2,TP1,start state,Material_3 instance N.298,4866.259009,R4
7722,7722.0,4865.677688,TR1,TP1,end state,Material_3 instance N.289,4865.677688,SK3,7722,4869.792173,TR2,TP1,end state,Material_2 instance N.308,4869.792173,S2
7723,7723.0,4865.677688,SK3,SK3,finished material,Material_3 instance N.289,NaN,NaN,7723,4869.792173,TR2,TP1,start state,Material_2 instance N.308,4871.275506,R1

In [11]:
df.loc[df['Material2'] == "Material_3 instance N.289"]

,Unnamed: 0,Time,Resource,State,Activity,Material,Expected End Time,Target location,Unnamed: 02,Time2,Resource2,State2,Activity2,Material2,Expected End Time2,Target location2
7161,7161.0,4610.779851,S3,S3,created material,Material_3 instance N.289,NaN,NaN,7161,4610.779851,S3,S3,created material,Material_3 instance N.289,NaN,NaN
7178,7178.0,4615.946079,TR1,TP1,start state,Material_3 instance N.289,4617.096079,S3,7178,4615.946079,TR1,TP1,start state,Material_3 instance N.289,4617.096079,S3
7179,7179.0,4617.096079,TR1,TP1,end state,Material_3 instance N.289,4617.096079,S3,7179,4617.096079,TR1,TP1,end state,Material_3 instance N.289,4617.096079,S3
7180,7180.0,4617.096079,TR1,TP1,start state,Material_3 instance N.289,4618.246079,R3,7180,4617.096079,TR1,TP1,start state,Material_3 instance N.289,4618.579413,R2
7181,7181.0,4618.246079,TR1,TP1,end state,Material_3 instance N.289,4618.246079,R3,7181,4618.579413,TR1,TP1,end state,Material_3 instance N.289,4618.579413,R2
7473,7472.0,4743.284033,SK1,SK1,finished material,Material_1 instance N.288,NaN,NaN,7473,4753.834844,R2,P2,start state,Material_3 instance N.289,4768.834844,NaN
7514,7514.0,4758.585805,TR1,TP1,end state,Material_1 instance N.301,4758.585805,R1,7514,4768.834844,R2,P2,end state,Material_3 instance N.289,4768.834844,NaN
7515,7515.0,4758.871223,TR2,TP1,end state,Material_2 instance N.295,4758.871223,R2,7515,4768.834844,TR2,TP1,start state,Material_3 instance N.289,4771.151511,R2
7517,7517.0,4759.861071,R3,P1,start state,Material_1 instance N.297,4777.704022,NaN,7517,4771.151511,TR2,TP1,end state,Material_3 instance N.289,4771.151511,R2
7518,7518.0,4759.861071,TR2,TP1,start state,Material_3 instance N.299,4760.344405,R3,7518,4771.151511,TR2,TP1,start state,Material_3 instance N.289,4771.968178,R4
7519,7519.0,4759.861071,R3,P3,start state,Material_3 instance N.285,4778.650316,NaN,7519,4771.968178,TR2,TP1,end state,Material_3 instance N.289,4771.968178,R4
7553,7553.0,4778.667455,R2,P2,end state,Material_1 instance N.286,4778.667455,NaN,7552,4794.336108,R4,P3,start state,Material_3 instance N.289,4811.922481,NaN
7572,7572.0,4794.336108,R4,P1,start state,Material_2 instance N.303,4805.472639,NaN,7572,4811.922481,R4,P3,end state,Material_3 instance N.289,4811.922481,NaN
7575,7575.0,4796.564103,TR1,TP1,start state,Material_2 instance N.271,4797.380770,R1,7575,4813.805637,TR2,TP1,start state,Material_3 instance N.289,4814.288970,R1
7576,7576.0,4797.380770,TR1,TP1,end state,Material_2 instance N.271,4797.380770,R1,7576,4814.288970,TR2,TP1,end state,Material_3 instance N.289,4814.288970,R1
7674,7674.0,4846.630770,TR1,TP1,start state,Material_3 instance N.307,4848.114103,S3,7674,4849.332184,R1,P1,start state,Material_3 instance N.289,4867.208165,NaN
7718,7718.0,4864.316220,TR2,TP1,end state,Material_2 instance N.302,4864.316220,R3,7718,4867.208165,R1,P1,end state,Material_3 instance N.289,4867.208165,NaN
7719,7719.0,4864.316220,TR2,TP1,start state,Material_2 instance N.302,4864.799553,R2,7719,4867.208165,TR1,TP1,start state,Material_3 instance N.289,4870.191498,R1
7724,7724.0,4865.949553,TR2,TP1,end state,Material_2 instance N.309,4865.949553,S2,7724,4870.191498,TR1,TP1,end state,Material_3 instance N.289,4870.191498,R1
7725,7725.0,4865.949553,TR2,TP1,start state,Material_2 instance N.309,4867.099553,R4,7725,4870.191498,TR1,TP1,start state,Material_3 instance N.289,4872.841498,SK3
7731,7731.0,4869.582887,TR2,TP1,end state,Material_1 instance N.293,4869.582887,SK1,7731,4872.841498,TR1,TP1,end state,Material_3 instance N.289,4872.841498,SK3
7733,7732.0,4869.582887,SK1,SK1,finished material,Material_1 instance N.293,NaN,NaN,7732,4872.841498,SK3,SK3,finished material,Material_3 instance N.289,NaN,NaN