In [38]:
import pandas as pd

In [39]:
df = pd.read_csv('data.csv')

In [40]:
df.head(20)

,Unnamed: 0,Time,Resource,State,Activtiy,Expected End Time,Material,Target location
0,0,14.532972,R3,Breakdownstate_2,start state,44.532972,NaN,NaN
1,1,34.609251,R1,P1,start state,51.965732,Material_1 instance N.0,NaN
2,2,44.532972,R3,Breakdownstate_2,end state,44.532972,NaN,NaN
3,3,47.596494,R3,Breakdownstate_2,start state,77.596494,NaN,NaN
4,4,51.789581,TR1,Breakdownstate_1,start state,81.789581,NaN,NaN
5,5,51.965732,R1,P1,end state,51.965732,Material_1 instance N.0,NaN
6,6,77.596494,R3,Breakdownstate_2,end state,77.596494,NaN,NaN
7,7,81.789581,TR1,Breakdownstate_1,end state,81.789581,NaN,NaN
8,8,81.789581,TR1,TP1,start state,82.050692,Material_1 instance N.0,R1
9,9,82.050692,TR1,TP1,end state,82.050692,Material_1 instance N.0,R1
10,10,82.050692,TR1,TP1,start state,82.311803,Material_1 instance N.0,R2
11,11,82.311803,TR1,TP1,end state,82.311803,Material_1 instance N.0,R2
12,12,82.311803,R2,P2,start state,97.311803,Material_1 instance N.0,NaN
13,13,89.448458,R3,P1,start state,104.338991,Material_1 instance N.1,NaN
14,14,93.487928,R1,P1,start state,97.266674,Material_2 instance N.2,NaN
15,15,97.266674,R1,P1,end state,97.266674,Material_2 instance N.2,NaN
16,16,97.266674,TR1,TP1,start state,97.527785,Material_2 instance N.2,R1
17,17,97.311803,R2,P2,end state,97.311803,Material_1 instance N.0,NaN
18,18,97.527785,TR1,TP1,end state,97.527785,Material_2 instance N.2,R1
19,19,97.527785,TR1,TP1,start state,97.788896,Material_2 instance N.2,R2

In [41]:
df.loc[df['Material'] == "Material_2 instance N.26"]

,Unnamed: 0,Time,Resource,State,Activtiy,Expected End Time,Material,Target location
423,424,845.518710,R3,P1,start state,857.795341,Material_2 instance N.26,NaN
426,425,854.814047,R3,P1,start interrupt,857.795341,Material_2 instance N.26,NaN
429,429,884.814047,R3,P1,end interrupt,887.795341,Material_2 instance N.26,NaN
430,430,884.814047,R3,P1,start state,887.795341,Material_2 instance N.26,NaN
432,432,887.795341,R3,P1,end state,887.795341,Material_2 instance N.26,NaN
438,438,917.750385,TR1,TP1,start state,917.900385,Material_2 instance N.26,R3
441,441,917.900385,TR1,TP1,end state,917.900385,Material_2 instance N.26,R3
451,454,953.517103,R3,P3,start state,978.543524,Material_2 instance N.26,NaN
472,472,978.543524,R3,P3,end state,978.543524,Material_2 instance N.26,NaN
473,473,978.543524,TR1,TP1,start state,978.804635,Material_2 instance N.26,R3
474,474,978.804635,TR1,TP1,end state,978.804635,Material_2 instance N.26,R3
475,475,978.804635,TR1,TP1,start state,979.065746,Material_2 instance N.26,R2
476,476,979.065746,TR1,TP1,end state,979.065746,Material_2 instance N.26,R2
487,487,998.778214,R2,P2,start state,1013.778214,Material_2 instance N.26,NaN
506,507,1013.778214,TR1,TP1,start state,1014.039326,Material_2 instance N.26,R2
507,506,1013.778214,R2,P2,end state,1013.778214,Material_2 instance N.26,NaN
509,510,1014.039326,TR1,TP1,start state,1014.300437,Material_2 instance N.26,R3
510,509,1014.039326,TR1,TP1,end state,1014.039326,Material_2 instance N.26,R2
511,511,1014.300437,TR1,TP1,end state,1014.300437,Material_2 instance N.26,R3
512,512,1014.300437,R3,P1,start state,1020.548403,Material_2 instance N.26,NaN
518,518,1020.548403,R3,P1,end state,1020.548403,Material_2 instance N.26,NaN

In [46]:
df.loc[df['Resource'] == "TR1"][180::].head(50)

,Unnamed: 0,Time,Resource,State,Activtiy,Expected End Time,Material,Target location
346,346,658.336036,TR1,TP1,start state,658.486036,Material_2 instance N.23,R2
348,348,658.486036,TR1,TP1,end state,658.486036,Material_2 instance N.23,R2
351,351,667.145816,TR1,Breakdownstate_1,start state,697.145816,NaN,NaN
359,359,697.145816,TR1,Breakdownstate_1,end state,697.145816,NaN,NaN
360,360,697.145816,TR1,TP1,start state,697.406927,Material_1 instance N.22,R1
361,361,697.406927,TR1,TP1,end state,697.406927,Material_1 instance N.22,R1
362,362,697.406927,TR1,TP1,start state,697.556927,Material_1 instance N.22,R1
363,363,697.556927,TR1,TP1,end state,697.556927,Material_1 instance N.22,R1
364,364,697.556927,TR1,TP1,start state,697.818038,Material_2 instance N.21,R2
366,367,697.818038,TR1,TP1,start state,698.079149,Material_2 instance N.21,R3
367,366,697.818038,TR1,TP1,end state,697.818038,Material_2 instance N.21,R2
369,369,698.079149,TR1,TP1,start state,698.451371,Material_2 instance N.24,R1
370,368,698.079149,TR1,TP1,end state,698.079149,Material_2 instance N.21,R3
371,371,698.451371,TR1,TP1,end state,698.451371,Material_2 instance N.24,R1
372,372,698.451371,TR1,TP1,start state,698.712482,Material_2 instance N.24,R2
373,373,698.712482,TR1,TP1,end state,698.712482,Material_2 instance N.24,R2
374,374,698.712482,TR1,TP1,start state,698.973594,Material_2 instance N.23,R1
376,376,698.973594,TR1,TP1,end state,698.973594,Material_2 instance N.23,R1
379,379,700.464296,TR1,TP1,start state,700.725407,Material_2 instance N.24,R2
380,380,700.725407,TR1,TP1,end state,700.725407,Material_2 instance N.24,R2
381,381,700.725407,TR1,TP1,start state,700.875407,Material_2 instance N.24,R2
383,382,700.875407,TR1,TP1,end state,700.875407,Material_2 instance N.24,R2
389,389,715.875407,TR1,TP1,start state,716.136518,Material_2 instance N.24,R1
390,390,716.136518,TR1,TP1,end state,716.136518,Material_2 instance N.24,R1
402,402,755.084854,TR1,TP1,start state,755.234854,Material_1 instance N.25,R1
403,403,755.234854,TR1,TP1,end state,755.234854,Material_1 instance N.25,R1
407,407,770.234854,TR1,TP1,start state,770.607077,Material_1 instance N.25,R3
408,408,770.607077,TR1,TP1,end state,770.607077,Material_1 instance N.25,R3
431,431,887.750385,TR1,Breakdownstate_1,start state,917.750385,NaN,NaN
437,437,917.750385,TR1,Breakdownstate_1,end state,917.750385,NaN,NaN
438,438,917.750385,TR1,TP1,start state,917.900385,Material_2 instance N.26,R3
441,441,917.900385,TR1,TP1,end state,917.900385,Material_2 instance N.26,R3
442,442,917.900385,TR1,TP1,start state,918.272608,Material_1 instance N.27,R1
443,443,918.272608,TR1,TP1,end state,918.272608,Material_1 instance N.27,R1
446,446,933.272608,TR1,TP1,start state,933.644830,Material_1 instance N.27,R3
447,447,933.644830,TR1,TP1,end state,933.644830,Material_1 instance N.27,R3
452,453,953.517103,TR1,TP1,start state,953.778214,Material_1 instance N.28,R2
455,455,953.778214,TR1,TP1,end state,953.778214,Material_1 instance N.28,R2
458,458,965.505851,TR1,TP1,start state,965.766962,Material_1 instance N.29,R3
460,460,965.766962,TR1,TP1,end state,965.766962,Material_1 instance N.29,R3
461,461,965.766962,TR1,TP1,start state,966.028073,Material_1 instance N.29,R2
462,462,966.028073,TR1,TP1,end state,966.028073,Material_1 instance N.29,R2
464,465,968.778214,TR1,TP1,start state,969.039326,Material_1 instance N.28,R1
467,467,969.039326,TR1,TP1,end state,969.039326,Material_1 instance N.28,R1
470,470,977.512859,TR1,TP1,start state,977.773971,Material_1 instance N.30,R2
471,471,977.773971,TR1,TP1,end state,977.773971,Material_1 instance N.30,R2
473,473,978.543524,TR1,TP1,start state,978.804635,Material_2 instance N.26,R3
474,474,978.804635,TR1,TP1,end state,978.804635,Material_2 instance N.26,R3
475,475,978.804635,TR1,TP1,start state,979.065746,Material_2 instance N.26,R2
476,476,979.065746,TR1,TP1,end state,979.065746,Material_2 instance N.26,R2