In [34]:
import pandas as pd

In [35]:
df = pd.read_csv('data.csv')

In [36]:
df.head(20)

,Unnamed: 0,Time,Resource,State,Activtiy,Expected End Time,Material,Target location
0,0,14.532972,R3,Breakdownstate_2,start state,44.532972,NaN,NaN
1,1,34.609251,R1,P1,start state,51.965732,Material_1 instance N.0,NaN
2,2,44.532972,R3,Breakdownstate_2,end state,44.532972,NaN,NaN
3,3,47.596494,R3,Breakdownstate_2,start state,77.596494,NaN,NaN
4,4,51.789581,TR1,Breakdownstate_1,start state,81.789581,NaN,NaN
5,5,51.965732,R1,P1,end state,51.965732,Material_1 instance N.0,NaN
6,6,77.596494,R3,Breakdownstate_2,end state,77.596494,NaN,NaN
7,8,81.789581,TR1,TP1,start state,81.845137,Material_1 instance N.0,R1
8,7,81.789581,TR1,Breakdownstate_1,end state,81.789581,NaN,NaN
9,9,81.845137,TR1,TP1,end state,81.845137,Material_1 instance N.0,R1
10,10,81.845137,TR1,TP1,start state,81.900692,Material_1 instance N.0,R2
11,11,81.900692,TR1,TP1,end state,81.900692,Material_1 instance N.0,R2
12,12,81.900692,R2,P2,start state,96.900692,Material_1 instance N.0,NaN
13,13,89.448458,R3,P1,start state,104.338991,Material_1 instance N.1,NaN
14,14,93.487928,R1,P1,start state,97.266674,Material_2 instance N.2,NaN
15,15,96.900692,R2,P2,end state,96.900692,Material_1 instance N.0,NaN
16,16,96.900692,TR1,TP1,start state,96.956248,Material_1 instance N.0,R1
17,18,96.956248,R1,P1,start state,113.409322,Material_1 instance N.0,NaN
18,17,96.956248,TR1,TP1,end state,96.956248,Material_1 instance N.0,R1
19,19,97.266674,R1,P1,end state,97.266674,Material_2 instance N.2,NaN

In [37]:
df.loc[df['Material'] == "Material_2 instance N.26"]

,Unnamed: 0,Time,Resource,State,Activtiy,Expected End Time,Material,Target location
393,393,842.699425,R3,P1,start state,855.351281,Material_2 instance N.26,NaN
395,395,855.351281,R3,P1,end state,855.351281,Material_2 instance N.26,NaN
396,396,855.351281,TR1,TP1,end state,763.347620,Material_2 instance N.26,R3
400,400,884.814047,R3,P3,start state,891.573719,Material_2 instance N.26,NaN
402,402,891.573719,R3,P3,end state,891.573719,Material_2 instance N.26,NaN
408,408,917.750385,TR1,TP1,start state,917.861496,Material_2 instance N.26,R1
411,413,917.861496,R1,P2,start state,932.861496,Material_2 instance N.26,NaN
412,411,917.861496,TR1,TP1,end state,917.861496,Material_2 instance N.26,R1
423,423,932.861496,R1,P2,end state,932.861496,Material_2 instance N.26,NaN
424,424,932.861496,TR1,TP1,start state,932.917052,Material_2 instance N.26,R1
425,425,932.917052,TR1,TP1,end state,932.917052,Material_2 instance N.26,R1
426,426,932.917052,TR1,TP1,start state,933.028163,Material_2 instance N.26,R3
430,428,933.028163,TR1,TP1,end state,933.028163,Material_2 instance N.26,R3
445,445,959.739153,R3,P1,start state,967.143537,Material_2 instance N.26,NaN
450,449,967.143537,R3,P1,end state,967.143537,Material_2 instance N.26,NaN

In [24]:
df.loc[df['Resource'] == "R3"][60::].head(50)

,Unnamed: 0,Time,Resource,State,Activtiy,Expected End Time,Material,Target location
336,336,697.201371,R3,P1,start state,709.478002,Material_1 instance N.22,NaN
349,349,709.478002,R3,P1,end state,709.478002,Material_1 instance N.22,NaN
362,362,745.033366,R3,Breakdownstate_1,start state,775.033366,NaN,NaN
377,377,775.033366,R3,Breakdownstate_1,end state,775.033366,NaN,NaN
378,378,775.033366,R3,P1,start state,782.699425,Material_2 instance N.24,NaN
379,379,775.033366,R3,Breakdownstate_2,start state,805.033366,NaN,NaN
380,380,775.033366,R3,P1,start interrupt,782.699425,Material_2 instance N.24,NaN
383,384,805.033366,R3,P1,end interrupt,812.699425,Material_2 instance N.24,NaN
384,385,805.033366,R3,P1,start state,812.699425,Material_2 instance N.24,NaN
385,383,805.033366,R3,Breakdownstate_2,end state,805.033366,NaN,NaN
386,386,810.479004,R3,Breakdownstate_1,start state,840.479004,NaN,NaN
387,387,810.479004,R3,P1,start interrupt,812.699425,Material_2 instance N.24,NaN
389,389,840.479004,R3,Breakdownstate_1,end state,840.479004,NaN,NaN
390,390,840.479004,R3,P1,end interrupt,842.699425,Material_2 instance N.24,NaN
391,391,840.479004,R3,P1,start state,842.699425,Material_2 instance N.24,NaN
392,393,842.699425,R3,P1,start state,855.351281,Material_2 instance N.26,NaN
393,392,842.699425,R3,P1,end state,842.699425,Material_2 instance N.24,NaN
394,394,854.814047,R3,Breakdownstate_1,start state,884.814047,NaN,NaN
395,395,855.351281,R3,P1,end state,855.351281,Material_2 instance N.26,NaN
398,398,884.814047,R3,Breakdownstate_1,end state,884.814047,NaN,NaN
399,399,884.814047,R3,P1,start state,896.802795,Material_1 instance N.27,NaN
400,400,884.814047,R3,P3,start state,891.573719,Material_2 instance N.26,NaN
402,402,891.573719,R3,P3,end state,891.573719,Material_2 instance N.26,NaN
404,404,896.802795,R3,P1,end state,896.802795,Material_1 instance N.27,NaN
405,405,910.865247,R3,P1,start state,929.739153,Material_1 instance N.28,NaN
409,409,917.811691,R3,Breakdownstate_1,start state,947.811691,NaN,NaN
410,410,917.811691,R3,P1,start interrupt,929.739153,Material_1 instance N.28,NaN
435,436,947.811691,R3,P1,end interrupt,959.739153,Material_1 instance N.28,NaN
436,437,947.811691,R3,P1,start state,959.739153,Material_1 instance N.28,NaN
437,435,947.811691,R3,Breakdownstate_1,end state,947.811691,NaN,NaN
444,445,959.739153,R3,P1,start state,967.143537,Material_2 instance N.26,NaN
446,444,959.739153,R3,P1,end state,959.739153,Material_1 instance N.28,NaN
449,449,967.143537,R3,P1,end state,967.143537,Material_2 instance N.26,NaN
450,450,967.143537,R3,P1,start state,973.391504,Material_1 instance N.29,NaN
452,452,973.391504,R3,P1,end state,973.391504,Material_1 instance N.29,NaN
461,461,988.502674,R3,P1,start state,1001.149185,Material_2 instance N.31,NaN
466,466,1001.149185,R3,P1,end state,1001.149185,Material_2 instance N.31,NaN
483,483,1018.599174,R3,P1,start state,1038.029902,Material_2 instance N.33,NaN
495,494,1038.029902,R3,P1,end state,1038.029902,Material_2 instance N.33,NaN
496,495,1038.029902,R3,P1,start state,1056.128786,Material_2 instance N.31,NaN
512,512,1056.128786,R3,P1,end state,1056.128786,Material_2 instance N.31,NaN
513,513,1056.128786,R3,P1,start state,1066.368552,Material_2 instance N.33,NaN
514,514,1066.368552,R3,P1,end state,1066.368552,Material_2 instance N.33,NaN
520,520,1069.145936,R3,P1,start state,1079.704276,Material_1 instance N.34,NaN
521,521,1079.704276,R3,P1,end state,1079.704276,Material_1 instance N.34,NaN
522,522,1089.255400,R3,P1,start state,1102.198709,Material_1 instance N.35,NaN
523,523,1102.198709,R3,P1,end state,1102.198709,Material_1 instance N.35,NaN
529,529,1115.745471,R3,P1,start state,1130.928851,Material_2 instance N.37,NaN
532,532,1130.928851,R3,P1,end state,1130.928851,Material_2 instance N.37,NaN
536,537,1142.540197,R3,P1,start state,1157.414945,Material_1 instance N.35,NaN