In [26]:
import pandas as pd

In [27]:
df = pd.read_csv('data.csv')

In [28]:
df.head(20)

,Unnamed: 0,Time,Resource,State,Activity,Expected End Time,Material,Target location
0,0,14.532972,R3,Breakdownstate_2,start state,44.532972,NaN,NaN
1,1,22.523481,R1,P1,start state,40.622365,Material_1 instance N.0,NaN
2,2,40.622365,R1,P1,end state,40.622365,Material_1 instance N.0,NaN
3,3,40.622365,TR1,TP1,start state,40.883477,Material_1 instance N.0,R1
4,4,40.883477,TR1,TP1,end state,40.883477,Material_1 instance N.0,R1
5,5,40.883477,TR1,TP1,start state,41.144588,Material_1 instance N.0,R2
6,6,41.144588,TR1,TP1,end state,41.144588,Material_1 instance N.0,R2
7,7,41.144588,R2,P2,start state,56.144588,Material_1 instance N.0,NaN
8,8,44.532972,R3,Breakdownstate_2,end state,44.532972,NaN,NaN
9,9,47.596494,R3,Breakdownstate_2,start state,77.596494,NaN,NaN
10,10,51.789581,TR1,Breakdownstate_1,start state,81.789581,NaN,NaN
11,11,54.760325,TR2,Breakdownstate_1,start state,84.760325,NaN,NaN
12,12,56.144588,R2,P2,end state,56.144588,Material_1 instance N.0,NaN
13,13,58.212488,R1,P1,start state,68.452255,Material_1 instance N.1,NaN
14,14,68.452255,R1,P1,end state,68.452255,Material_1 instance N.1,NaN
15,15,77.596494,R3,Breakdownstate_2,end state,77.596494,NaN,NaN
16,16,77.596494,R3,P1,start state,94.055294,Material_2 instance N.2,NaN
17,17,81.789581,TR1,Breakdownstate_1,end state,81.789581,NaN,NaN
18,18,81.789581,TR1,TP1,start state,82.050692,Material_1 instance N.0,R3
19,19,82.050692,TR1,TP1,end state,82.050692,Material_1 instance N.0,R3

In [29]:
df.loc[df['Material'] == "Material_2 instance N.26"]

,Unnamed: 0,Time,Resource,State,Activity,Expected End Time,Material,Target location
376,376,528.492451,R1,P1,start state,539.882894,Material_2 instance N.26,NaN
389,388,538.947700,R1,P1,start interrupt,539.882894,Material_2 instance N.26,NaN
399,399,568.947700,R1,P1,end interrupt,569.882894,Material_2 instance N.26,NaN
401,400,568.947700,R1,P1,start state,569.882894,Material_2 instance N.26,NaN
403,403,569.882894,R1,P1,end state,569.882894,Material_2 instance N.26,NaN
404,404,569.882894,TR2,TP1,start state,570.144005,Material_2 instance N.26,R2
405,405,570.144005,TR2,TP1,end state,570.144005,Material_2 instance N.26,R2
407,407,580.750808,R2,P3,start state,600.172237,Material_2 instance N.26,NaN
415,415,600.172237,R2,P3,end state,600.172237,Material_2 instance N.26,NaN
416,416,600.172237,TR1,TP1,start state,600.322237,Material_2 instance N.26,R2
417,417,600.322237,TR1,TP1,end state,600.322237,Material_2 instance N.26,R2
418,418,600.322237,R2,P2,start state,615.322237,Material_2 instance N.26,NaN
428,428,615.322237,R2,P2,end state,615.322237,Material_2 instance N.26,NaN
430,430,615.322237,TR2,TP1,start state,615.583348,Material_2 instance N.26,R3
431,431,615.583348,TR2,TP1,end state,615.583348,Material_2 instance N.26,R3
432,432,615.583348,R3,P1,start state,630.740637,Material_2 instance N.26,NaN
443,443,630.740637,R3,P1,end state,630.740637,Material_2 instance N.26,NaN

In [30]:
df.loc[df['Resource'] == "R3"][180::].head(50)

,Unnamed: 0,Time,Resource,State,Activity,Expected End Time,Material,Target location
1110,1110,1388.227519,R3,Breakdownstate_1,end state,1388.227519,NaN,NaN
1111,1111,1388.227519,R3,P1,end interrupt,1392.535686,Material_2 instance N.56,NaN
1112,1112,1388.227519,R3,P1,start state,1392.535686,Material_2 instance N.56,NaN
1118,1118,1392.535686,R3,P1,end state,1392.535686,Material_2 instance N.56,NaN
1119,1119,1392.535686,R3,P1,start state,1417.493434,Material_1 instance N.63,NaN
1120,1120,1392.535686,R3,P3,start state,1399.510473,Material_2 instance N.70,NaN
1121,1123,1395.001687,R3,Breakdownstate_1,start state,1425.001687,NaN,NaN
1122,1121,1395.001687,R3,P1,start interrupt,1417.493434,Material_1 instance N.63,NaN
1123,1122,1395.001687,R3,P3,start interrupt,1399.510473,Material_2 instance N.70,NaN
1146,1146,1425.001687,R3,Breakdownstate_1,end state,1425.001687,NaN,NaN
1147,1147,1425.001687,R3,P1,end interrupt,1447.493434,Material_1 instance N.63,NaN
1148,1149,1425.001687,R3,P3,end interrupt,1429.510473,Material_2 instance N.70,NaN
1149,1148,1425.001687,R3,P1,start state,1447.493434,Material_1 instance N.63,NaN
1150,1150,1425.001687,R3,P3,start state,1429.510473,Material_2 instance N.70,NaN
1151,1153,1425.001687,R3,Breakdownstate_2,start state,1455.001687,NaN,NaN
1152,1151,1425.001687,R3,P1,start interrupt,1447.493434,Material_1 instance N.63,NaN
1153,1152,1425.001687,R3,P3,start interrupt,1429.510473,Material_2 instance N.70,NaN
1176,1176,1455.001687,R3,Breakdownstate_2,end state,1455.001687,NaN,NaN
1177,1177,1455.001687,R3,P1,end interrupt,1477.493434,Material_1 instance N.63,NaN
1178,1179,1455.001687,R3,P3,end interrupt,1459.510473,Material_2 instance N.70,NaN
1179,1178,1455.001687,R3,P1,start state,1477.493434,Material_1 instance N.63,NaN
1180,1180,1455.001687,R3,P3,start state,1459.510473,Material_2 instance N.70,NaN
1181,1181,1459.510473,R3,P3,end state,1459.510473,Material_2 instance N.70,NaN
1182,1182,1459.510473,R3,P3,start state,1472.714032,Material_2 instance N.68,NaN
1194,1194,1472.714032,R3,P3,end state,1472.714032,Material_2 instance N.68,NaN
1199,1200,1474.775101,R3,Breakdownstate_2,start state,1504.775101,NaN,NaN
1200,1199,1474.775101,R3,P1,start interrupt,1477.493434,Material_1 instance N.63,NaN
1214,1214,1504.775101,R3,Breakdownstate_2,end state,1504.775101,NaN,NaN
1215,1215,1504.775101,R3,P1,end interrupt,1507.493434,Material_1 instance N.63,NaN
1216,1216,1504.775101,R3,P1,start state,1507.493434,Material_1 instance N.63,NaN
1217,1218,1504.775101,R3,Breakdownstate_1,start state,1534.775101,NaN,NaN
1218,1217,1504.775101,R3,P1,start interrupt,1507.493434,Material_1 instance N.63,NaN
1231,1231,1534.775101,R3,Breakdownstate_1,end state,1534.775101,NaN,NaN
1232,1232,1534.775101,R3,P1,end interrupt,1537.493434,Material_1 instance N.63,NaN
1233,1233,1534.775101,R3,P1,start state,1537.493434,Material_1 instance N.63,NaN
1234,1234,1537.493434,R3,P1,end state,1537.493434,Material_1 instance N.63,NaN
1235,1235,1537.493434,R3,P1,start state,1549.689456,Material_2 instance N.61,NaN
1242,1242,1549.689456,R3,P1,end state,1549.689456,Material_2 instance N.61,NaN
1243,1243,1549.689456,R3,P1,start state,1569.560461,Material_2 instance N.73,NaN
1254,1254,1569.560461,R3,P1,end state,1569.560461,Material_2 instance N.73,NaN
1255,1255,1569.560461,R3,P1,start state,1575.583608,Material_1 instance N.71,NaN
1260,1260,1575.583608,R3,P1,end state,1575.583608,Material_1 instance N.71,NaN
1261,1261,1575.583608,R3,P1,start state,1587.559594,Material_2 instance N.62,NaN
1273,1274,1583.300690,R3,Breakdownstate_2,start state,1613.300690,NaN,NaN
1274,1273,1583.300690,R3,P1,start interrupt,1587.559594,Material_2 instance N.62,NaN
1292,1292,1613.300690,R3,Breakdownstate_2,end state,1613.300690,NaN,NaN
1293,1293,1613.300690,R3,P1,end interrupt,1617.559594,Material_2 instance N.62,NaN
1294,1294,1613.300690,R3,P1,start state,1617.559594,Material_2 instance N.62,NaN
1295,1295,1617.559594,R3,P1,end state,1617.559594,Material_2 instance N.62,NaN
1296,1296,1617.559594,R3,P1,start state,1636.120747,Material_2 instance N.64,NaN

In [31]:
print(df['Activity'].unique())

['start state' 'end state' 'start interrupt' 'end interrupt']